### ISSUE TITLE
import model

### ISSUE THREAD

**Issue by gpwood** [hesther/espsim#12] opened 2022-02-04 15:00 UTC
Hello,

I just downloaded this package and excited to use it. However, when I run benchmark_1_partial_charges.ipynb I'm getting this warning for the ML predictions:
    
    Computing ML charges (will print three warnings for failed predictions)
    Warning: could not obtain prediction, defaulting to Gasteiger charges for one molecule
    Warning: could not obtain prediction, defaulting to Gasteiger charges for one molecule
    Warning: could not obtain prediction, defaulting to Gasteiger charges for one molecule

Do I need to worry about this?

Thanks and have a nice day!

**Comment by hesther** [comment] 2022-02-04 15:07
Hi @gpwood Yes that's fine (that's what the sentence in brackets was supposed to imply). There are unfortunately three molecules for which the ML prediction fails, so it defaults to Gasteiger charges. 

The failure is due to the way the ML model is implemented (taking as input SMILES not molecules). For three molecules saving them to SMILES and reloading the molecule doesn't reproduce the initial molecule. At some point I want to change the ML model to take molecules instead of SMILES as input, because that would alleviate this problem, as well as make the code faster since the atoms don't need to be reordered. I haven't come around to it yet, though.

On a side note: If you want to try ML charges on your own molecules, always make sure to use explicit hydrogens, otherwise the ML model will fail, too (I should probably introduce a better warning then).

**Comment by hesther** [comment] 2022-09-02 19:44
Closing this since I believe it was solved (if not, feel free to reopen!)

**Closed by hesther** 2022-09-02 19:44 UTC
